type Message {
  text: String!
  user: String!
}

type Subscription {
  newMessage: Message!
}

type Query {
  messages: [Message]!
}

type Mutation {
  sendMessage(user: String!, text: String!): Boolean!
}
